<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tig</string>
	</array>
	<key>name</key>
	<string>Tiger</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#binary-operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literal-function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literal-typedef</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-call</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#var-init</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#array-create</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#record-create</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#braces</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array-create</key>
		<dict>
			<key>match</key>
			<string>([[:alpha:]][_[:alnum:]]*)(?=\s*\[.*\]\s*of\b)</string>
			<key>name</key>
			<string>entity.name.class.tig</string>
		</dict>
		<key>assignment</key>
		<dict>
			<key>match</key>
			<string>:=|=</string>
			<key>name</key>
			<string>keyword.operator.assignment.tig</string>
		</dict>
		<key>binary-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;\=|&gt;\=|\=\=|&lt;|&gt;|\!\=</string>
					<key>name</key>
					<string>keyword.operator.comparison.tig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|\-|\*|/|&amp;|\|</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.tig</string>
				</dict>
			</array>
		</dict>
		<key>braces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{</string>
					<key>name</key>
					<string>punctuation.definition.block.tig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\}</string>
					<key>name</key>
					<string>punctuation.definition.block.tig</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.tig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.tig</string>
				</dict>
			</array>
		</dict>
		<key>function-call</key>
		<dict>
			<key>match</key>
			<string>([[:alpha:]][_[:alnum:]]*)(?=\s*\()</string>
			<key>name</key>
			<string>variable.function.tig</string>
		</dict>
		<key>function-declaration-parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.begin.tig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.end.tig</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([[:alpha:]][_[:alnum:]]*)</string>
							<key>name</key>
							<string>variable.parameter.function.tig</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.parameter.function.tig</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function-param-type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-param-type</key>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.tig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=[,)])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([[:alpha:]][_[:alnum:]]*)</string>
					<key>name</key>
					<string>entity.name.class.tig</string>
				</dict>
			</array>
		</dict>
		<key>function-return-type</key>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.tig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\=)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([[:alpha:]][_[:alnum:]]*)</string>
					<key>name</key>
					<string>entity.name.class.tig</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|for|while|to|do|then|break)\b</string>
					<key>name</key>
					<string>keyword.control.tig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(let|in|end)\b</string>
					<key>name</key>
					<string>keyword.other.tig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(array|primitive|of)\b</string>
					<key>name</key>
					<string>storage.type.tig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(nil)\b</string>
					<key>name</key>
					<string>constant.language.tig</string>
				</dict>
			</array>
		</dict>
		<key>literal-function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x)
  \b(function)
  \s*([[:alpha:]][_[:alnum:]]*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.tig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.tig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\=)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#function-declaration-parameters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function-return-type</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#assignment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>literal-typedef</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?x)
  \b(type)
  \s*([[:alpha:]][_[:alnum:]]*)\s*(?=\=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.tig</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.tig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#assignment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([[:alpha:]][_[:alnum:]]*)</string>
							<key>name</key>
							<string>entity.name.class.tig</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#typedef-record-parameters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b([0-9][\d]*)</string>
					<key>name</key>
					<string>constant.numeric.integer.decimal.tig</string>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.statement.tig</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.tig</string>
				</dict>
			</array>
		</dict>
		<key>record-create</key>
		<dict>
			<key>match</key>
			<string>([[:alpha:]][_[:alnum:]]*)(?=\s*\{)</string>
			<key>name</key>
			<string>entity.name.class.tig</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.tig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.tig</string>
				</dict>
			</array>
		</dict>
		<key>typedef-record-param-type</key>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.tig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=[,}])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([[:alpha:]][_[:alnum:]]*)</string>
					<key>name</key>
					<string>entity.name.class.tig</string>
				</dict>
			</array>
		</dict>
		<key>typedef-record-parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.braces.begin.tig</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.braces.end.tig</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([[:alpha:]][_[:alnum:]]*)</string>
							<key>name</key>
							<string>variable.parameter.function.tig</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.parameter.function.tig</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#typedef-record-param-type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>var-init</key>
		<dict>
			<key>begin</key>
			<string>\b(var)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>storage.type.tig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\:\=</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.tig</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#var-init-param-type</string>
				</dict>
			</array>
		</dict>
		<key>var-init-param-type</key>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.tig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\:\=)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([[:alpha:]][_[:alnum:]]*)</string>
					<key>name</key>
					<string>entity.name.class.tig</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.tig</string>
	<key>uuid</key>
	<string>65707da3-b0b0-4975-a180-b4611d0edfda</string>
</dict>
</plist>
